### PR TITLE
split line into 2 sub-expressions

### LINKED ISSUE #53: My build fails because of HDWalletKit
After installing HDWalletKit via cocoaPods, my build fails with following error:

```

HDWalletKit/HDWalletKit/Core/BitcoinScript/Script.swift:455:107: error: 
the compiler is unable to type-check this expression in reasonable time; 
try breaking up the expression into distinct sub-expressions

```

In development I have fixed this by breaking up mentioned line of code into 2
But now that I want to perform `pod lint lib` or publish it, it fails
both on my machine and on travis

### PR DESCRIPTION
**Pull request by leviathanbeak**
I want to resolve #53 with splitting one long line of code into 2 sub-expressions

### CODE REVIEW

**Comment by impul** [comment]
## Migration Recommended

It appears you are still using the CoPilot OAuth App - we recommend you [migrate to the GitHub App](https://github.com/apps/blackduck-copilot/installations/new/permissions?suggested_target_id=32127946&repository_ids[]=138875033&repository_ids[]=138898540)

**Comment by impul** [comment]
## Migration Recommended

It appears you are still using the CoPilot OAuth App - we recommend you [migrate to the GitHub App](https://github.com/apps/blackduck-copilot/installations/new/permissions?suggested_target_id=32127946&repository_ids[]=138875033&repository_ids[]=138898540)

**Comment by impul** [comment]
## Black Duck Security Report

Merging #54 into develop will not change security risk.

### Removed Components

Clean:       2

[Click here to see full report](https://copilot.blackducksoftware.com/github/repos/essentiaone/HDWallet/pull-requests/54)

**Comment by impul** [comment]
## Black Duck Security Report

Merging #54 into develop will not change security risk.

### Removed Components

Clean:       2

[Click here to see full report](https://copilot.blackducksoftware.com/github/repos/essentiaone/HDWallet/pull-requests/54)

**Comment by impul** [comment]
Hi @leviathan88, this looks not the best to every time adding new tmp :)
Could you create array of UInt8 from OP-codes and use Data(<#T##elements: Sequence##Sequence#>) init to create Data?

**Comment by leviathanbeak** [comment]
@impul not sure I understood everything, also does order of codes matter

is it possible to do something like this

```
let opCodes: [UInt8] = [
            OpCode.OP_DUP.value,
            OpCode.OP_HASH160.value,
            UInt8(pubKeyHash.count),
            OpCode.OP_EQUALVERIFY.value,
            OpCode.OP_CHECKSIG.value
]
return Data.init(opCodes) + pubKeyHash
```

could you provide more input ?

**Comment by impul** [comment]
@leviathan88 yes, it matters. You've done almost right. Just do [[UInt8]] and flat map over them.

**Comment by leviathanbeak** [comment]
@impul and map it to what ? could you be more clear I want to help, thanks

**Comment by impul** [comment]
@leviathan88, here is how I see it, flat map would not work here, sorry for confusing: 
```Swift
let values: [UInt8] =
         [OpCode.OP_DUP.value, OpCode.OP_HASH160.value, UInt8(pubKeyHash.count)]
         + pubKeyHash.bytes
         + [OpCode.OP_EQUALVERIFY.value,  OpCode.OP_CHECKSIG.value]
return Data(values)
```

And also we need Unit-test for that: 
```Swift
    func testPublickKeyHashOutFromPubKeyHash() {
        let expected = "76a9210392030131e97b2a396691a7c1d91f6b5541649b75bda14d056797ab3cadcaf2f588ac"
        let entropy = Data(hex: "000102030405060708090a0b0c0d0e0f")
        let mnemonic = Mnemonic.create(entropy: entropy)
        let seed = Mnemonic.createSeed(mnemonic: mnemonic)
        let privateKey = PrivateKey(seed: seed, coin: .bitcoin)
        let publicKey = privateKey.publicKey.data
        let hash = Script.buildPublicKeyHashOut(pubKeyHash: publicKey)
        XCTAssertEqual(hash.toHexString(), expected)
    }
```

**Comment by leviathanbeak** [comment]
@impul no problem, that seems to work, and I can do it like that but I'm afraid that line would once again be too long, what do you say we do it like this:

```
let values: [[UInt8]] = [
            [OpCode.OP_DUP.value, OpCode.OP_HASH160.value, UInt8(pubKeyHash.count)],
            pubKeyHash.bytes,
            [OpCode.OP_EQUALVERIFY.value,  OpCode.OP_CHECKSIG.value]
]
 return Data(values.reduce([], +))
```

**Comment by impul** [comment]
@leviathan88 it should not, I but your solution is also good. And don't forget about tests, thank you for your support.

**Comment by leviathanbeak** [comment]
@impul thank you, one last thing in which Test file should I include the test, thanks!

**Comment by impul** [comment]
@leviathan88 in `CryptoTests`

**Pull request merged**
