### PR TITLE
Fix compile on Xcode 11

### PR DESCRIPTION
**Pull request by iartemov**

### CODE REVIEW

**Comment by impul** [comment]
## Migration Recommended

It appears you are still using the CoPilot OAuth App - we recommend you [migrate to the GitHub App](https://github.com/apps/blackduck-copilot/installations/new/permissions?suggested_target_id=32127946&repository_ids[]=138875033&repository_ids[]=138898540)

**Comment by impul** [comment]
## Black Duck Security Report

Merging #48 into develop will not change security risk.

[Click here to see full report](https://copilot.blackducksoftware.com/github/repos/essentiaone/HDWallet/pull-requests/48)

**Review by impul — APPROVED** [review]

**Comment by iartemov** [comment]
@impul Need one more approve, but there are only one reviewer as I see. Who can make another approve?

**Review by emilabduselimov — APPROVED** [review]

**Comment by impul** [comment]
@iartemov, i already do not work on Essentia, so unfortunately I can not merge it :( 
You can just clone it to your project, and use it as target in workspace.

**Pull request merged**
